### PR TITLE
fix HTTPS support

### PR DESCRIPTION
**Pull request by freddy36**
WebSocket, Artwork and Playback support with HTTPS was broken

### CODE REVIEW

**Comment by LukePulverenti** [comment]
Awesome. If we're talking good, better, best, I would label this as better. 

What would be best would be to have a single value called serverUrl that contains. This way the concatenation of protocol, host and port only has to happen in one place.

httpProtocol + "://" + server

**Comment by freddy36** [comment]
I fully agree.
This is just some basic patch to make it actually work.
There's a lot of cleanup potential regarding HTTP.
I plan to work on a patch to reduce the amount of redundant code later.

**Comment by angelblue05** [comment]
The HTTPS is already set in the windows property. Just need to call currUser then server%s % username with window getproperty. This will return to you http/s://server:port.

**Comment by LukePulverenti** [comment]
Well maybe it is but it looks like it's not being used everywhere that it should. Also, null_pointer has generally discouraged using window properties from non-ui classes. It sounds like you might be better off having the window get it from some connection management object rather than the other way around.

**Comment by angelblue05** [comment]
It's not being used because I just made the userClient and haven't had the chance to plug it in yet lol. It's being used for DownloadUtils currently and working so far. Just haven't had the chance to go over the rest of the modules. :) Windows property are just fine, if you set a value to make sure they don't override eachother when profile switching which I've made sure it would be fine.

**Comment by xnappo** [comment]
Please discuss this on the forum instead of on Git.

Luke - window properties are fine to use.

**Comment by freddy36** [comment]
no longer needed

**Pull request closed without merging**
